  - name: Ensure builds directory
    become_user: "{{ lookup('env', 'USER') }}"
    file:
      path: "{{ lookup('env', 'HOME') }}/Projects/builds"
      state: directory
    tags:
      - install
      - core

  - name: Ensure personal directory
    become_user: "{{ lookup('env', 'USER') }}"
    file:
      path: "{{ lookup('env', 'HOME') }}/Projects/personal"
      state: directory
    tags:
      - install
      - core

  - name: Ensure school directory
    become_user: "{{ lookup('env', 'USER') }}"
    file:
      path: "{{ lookup('env', 'HOME') }}/Projects/school"
      state: directory
    tags:
      - install
      - core

  - name: Ensure work directory
    become_user: "{{ lookup('env', 'USER') }}"
    file:
      path: "{{ lookup('env', 'HOME') }}/Projects/work"
      state: directory
    tags:
      - install
      - core

  - name: Ensure local bin directory
    become_user: "{{ lookup('env', 'USER') }}"
    file:
      path: "{{ lookup('env', 'HOME') }}/.local/bin"
      state: directory
    tags:
      - install
      - core

  - name: Install system utils (apt)
    when: ansible_os_family == "Debian"
    become: true
    apt:
      name: 
        - ninja-build
        - gettext
        - cmake
        - unzip
        - curl
        - libtool
        - libtool-bin
        - python3
        - python3-pip
        - libdbus-1-dev 
        - pkg-config
        - build-essential
    tags:
      - install
      - core

  - name: Install system utils (dnf)
    when: ansible_os_family == "RedHat"
    become: true
    dnf:
      name: 
        - ninja-build
        - gettext
        - cmake
        - unzip
        - curl
        - libtool
        - python3
        - python3-pip
        - dbus-devel 
        - pkgconf-pkg-config
        - "@development-tools"
    tags:
      - install
      - core

  - name: Install system tools (apt)
    when: ansible_os_family == "Debian"
    become: true
    apt:
      name: 
        - zsh
        - tmux
        - git
        - fd-find
        - ripgrep
        - curl
        - btop
        - bat
        - xclip
        - wl-clipboard
        - latexmk
        - texlive
        - texlive-lipsum
        - texlive-apacite
        - texlive-babel-norsk
        - texlive-hyphen-norwegian
        - tldr
        - rclone
    tags:
      - install
      - core

  - name: Install system tools (dnf)
    when: ansible_os_family == "RedHat"
    become: true
    dnf:
      name: 
        - zsh
        - tmux
        - git
        - fd-find
        - ripgrep
        - curl
        - btop
        - bat
        - latexmk
        - texlive
        - texlive-texcount
        - texlive-lipsum
        - texlive-tikzfill
        - texlive-listingsutf8
        - texlive-tabto-ltx
        - texlive-tcolorbox
        - texlive-wrapfig
        - texlive-apacite
        - texlive-babel-norsk
        - texlive-hyphen-norwegian
        - xclip
        - wl-clipboard
        - tldr
        - rclone
        - neovim
    tags:
      - install
      - core

  - name: Symlink fd
    when: ansible_os_family == "Debian"
    file:
      src: "/usr/bin/fdfind"
      dest: "{{ lookup('env', 'HOME') }}/.local/bin/fd"
      state: link
