- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles

- name: Cloning .dotfiles
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: "git@github.com:kojogadget/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
  tags:
    - install
    - dotfiles

- name: Stow dotfiles
  become_user: "{{ lookup('env', 'USER') }}"
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
