- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "kjartan@gunder.dev"
  tags:
    - install
    - git-personal

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Kjartan Gundersen"
  tags:
    - install
    - install
    - git-personal
