  - name: Install gui programs (dnf)
    when: ansible_os_family == "RedHat"
    become: true
    dnf:
      state: "present"
      name: 
        - firefox
        - foot
        - alacritty
        - rofi
        - zathura
        - zathura-pdf-mupdf 
        - zathura-zsh-completion
    tags:
      - gui

