  - name: Remove Neovim
    shell: rm -rf {{ lookup('env', 'HOME') }}/Projects/builds/neovim
    tags: 
      - install
      - neovim

  - name: Clone Neovim
    ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim.git'
      dest: "{{ lookup('env', 'HOME') }}/Projects/builds/neovim"
    tags:
      - install
      - neovim

  - name: Build neovim
    shell: "cd {{ lookup('env', 'HOME') }}/Projects/builds/neovim && git checkout stable && make CMAKE_BUILD_TYPE=RelWithDebInfo"
    tags:
      - install
      - neovim

  - name: Install neovim
    become: true
    shell: "cd {{ lookup('env', 'HOME') }}/Projects/builds/neovim && make install"
    tags:
      - install
      - neovim

  - name: Neovim Dependencies 1 luarocks
    become: true
    package: name=luarocks
    tags:
      - install
      - neovim

  - name: Neovim Dependencies 2 luacheck
    become: true
    shell: luarocks install luacheck
    tags:
      - install
      - neovim
