- name: Install nvm
  become_user: "{{ lookup('env', 'USER') }}"
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  tags:
    - install
    - node

- name: Load NVM and install Node.js
  become_user: "{{ lookup('env', 'USER') }}"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
  tags: 
    - install
    - node

- name: Install npm global tree-sitter-cli, neovim
  become_user: "{{ lookup('env', 'USER') }}"
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm i -g tree-sitter-cli neovim eslint typescript-language-server typescript ts-node
  tags:
    - install
    - node
