- name: Ensure .ssh directory exists
  become_user: "{{ lookup('env', 'USER') }}"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh

- name: Install ssh key
  become_user: "{{ lookup('env', 'USER') }}"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - install
    - ssh

- name: Install ssh key public
  become_user: "{{ lookup('env', 'USER') }}"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - install
    - ssh

- name: Read the public key content
  slurp:
    src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  register: public_key_file
  tags:
    - install
    - ssh

- name: Set authorized key took from file
  become_user: "{{ lookup('env', 'USER') }}"
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ public_key_file.content | b64decode }}"
  tags:
    - install
    - ssh
