- name: Install starship
  become_user: "{{ lookup('env', 'USER') }}"
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  tags:
    - install
    - utils
    - starship

- name: Install rust tools (zoxide, eza, bluetui)
  become_user: "{{ lookup('env', 'USER') }}"
  community.general.cargo:
    name: 
      - zoxide
      - eza
      - bluetui
    executable: "{{ lookup('env', 'HOME' ) }}/.cargo/bin/cargo"
    locked: true
  tags:
    - install
    - utils

- name: Install python tools (pulsemixer)
  become_user: "{{ lookup('env', 'USER') }}"
  pip:
    name: 
      - pulsemixer
  tags:
    - install
    - utils

- name: Install fzf 
  become_user: "{{ lookup('env', 'USER') }}"
  shell: cd {{ lookup('env', 'HOME') }}/.fzf && ./install
  tags:
    - install
    - utils
    - fzf
